struct QuestionBank {
    static let pythonQuestions: [Question] = [
        Question(text: "What is the correct syntax to output 'Hello World' in Python?",
                 options: ["echo 'Hello World'", "printf('Hello World')", "print('Hello World')", "Console.WriteLine('Hello World')"],
                 correctAnswer: "print('Hello World')"),
        Question(text: "What data type is returned by the function input() in Python?",
                 options: ["int", "float", "string", "list"],
                 correctAnswer: "string"),
        Question(text: "Which of the following is used to handle exceptions in Python?",
                 options: ["try-catch", "try-except", "error-handling", "exception-handler"],
                 correctAnswer: "try-except"),
        Question(text: "What does the len() function do in Python?",
                 options: ["Calculates the length of a string or list", "Deletes an element", "Counts the number of variables", "Splits a string"],
                 correctAnswer: "Calculates the length of a string or list"),
        Question(text: "Which of the following is NOT a Python keyword?",
                 options: ["lambda", "eval", "pass", "class"],
                 correctAnswer: "eval"),
        Question(text: "How is a comment written in Python?",
                 options: ["// This is a comment", "# This is a comment", "<!-- This is a comment -->", "' This is a comment"],
                 correctAnswer: "# This is a comment"),
        Question(text: "What is the result of 3 * 1 ** 3 in Python?",
                 options: ["3", "1", "9", "27"],
                 correctAnswer: "3"),
        Question(text: "Which of these is a valid Python dictionary?",
                 options: ["{1, 2, 3}", "[1: 'a', 2: 'b']", "{1: 'a', 2: 'b'}", "(1, 'a'), (2, 'b')"],
                 correctAnswer: "{1: 'a', 2: 'b'}"),
        Question(text: "How do you create a list in Python?",
                 options: ["list = (1, 2, 3)", "list = {1, 2, 3}", "list = [1, 2, 3]", "list = <1, 2, 3>"],
                 correctAnswer: "list = [1, 2, 3]"),
        Question(text: "What does break do in a loop?",
                 options: ["Skips an iteration", "Terminates the loop", "Exits the program", "Restarts the loop"],
                 correctAnswer: "Terminates the loop"),
        Question(text: "Which keyword is used to define a function in Python?",
                 options: ["define", "def", "func", "lambda"],
                 correctAnswer: "def"),
        Question(text: "What is the output of type({}) in Python 3?",
                 options: ["<class 'dict'>", "<class 'list'>", "<class 'set'>", "<class 'tuple'>"],
                 correctAnswer: "<class 'dict'>"),
        Question(text: "Which module in Python is used to generate random numbers?",
                 options: ["math", "random", "numbers", "numpy"],
                 correctAnswer: "random"),
        Question(text: "Which of the following is a mutable data type in Python?",
                 options: ["tuple", "string", "list", "frozenset"],
                 correctAnswer: "list"),
        Question(text: "What is the output of bool([]) in Python?",
                 options: ["True", "False", "Error", "None"],
                 correctAnswer: "False"),
        Question(text: "What does the is operator compare in Python?",
                 options: ["Value of variables", "Type of variables", "Identity of objects", "Length of variables"],
                 correctAnswer: "Identity of objects"),
        Question(text: "What is the correct syntax to read a file in Python?",
                 options: ["open('file.txt', 'read')", "open('file.txt', 'r')", "open.read('file.txt')", "file.read('file.txt')"],
                 correctAnswer: "open('file.txt', 'r')"),
        Question(text: "Which of the following methods can be used to find the largest element in a list?",
                 options: ["max()", "largest()", "big()", "size()"],
                 correctAnswer: "max()"),
        Question(text: "What is the output of list(range(5))?",
                 options: ["[1, 2, 3, 4, 5]", "[0, 1, 2, 3, 4, 5]", "[0, 1, 2, 3, 4]", "Error"],
                 correctAnswer: "[0, 1, 2, 3, 4]"),
        Question(text: "Which of the following libraries is used for data visualization in Python?",
                 options: ["pandas", "numpy", "matplotlib", "tensorflow"],
                 correctAnswer: "matplotlib"),
        Question(text: "Which of the following is a valid variable name in Python?",
                 options: ["1var", "_var", "var-name", "var name"],
                 correctAnswer: "_var"),
        Question(text: "How do you perform integer division in Python?",
                 options: ["//", "%", "/", "div()"],
                 correctAnswer: "//"),
        Question(text: "What is the output of print(2 ** 3) in Python?",
                 options: ["6", "8", "9", "16"],
                 correctAnswer: "8"),
        Question(text: "Which of the following is used to create a class in Python?",
                 options: ["struct", "object", "class", "define"],
                 correctAnswer: "class"),
        Question(text: "Which keyword is used to import libraries in Python?",
                 options: ["include", "import", "package", "library"],
                 correctAnswer: "import")
    ]
    // Add Java, C++, and JavaScript questions here following the same structure.
}
